### ISSUE TITLE
Rapla client doesn't start anymore

### ISSUE THREAD

**Issue by quenenni** [rapla/rapla#552]
Hello,

We had a functionning instance of Rapla but today, the client doesn't want to start anymore.

The server is working normally from what I gather (no error in logs and status shows it's running).
Direct data access is still working (I can use a link like this one to get an .ics file with the data: `"GET /rapla?page=ical&user=xxx&file=XXXXX HTTP/1.1" 200`)

But the client won't start.
The commande `javaws "http://xxx.yyy.zzz:8051/rapla/raplaclient.jnlp"` returns this error:
* Server side (no error here):
```
"HEAD /rapla/raplaclient.jnlp HTTP/1.1" 200 1269
"GET /rapla/raplaclient.jnlp HTTP/1.1" 200 1269
"HEAD /webclient/logo.png HTTP/1.1" 200 0
"HEAD /webclient/gson-2.3.1.jar HTTP/1.1" 200 0
"HEAD /webclient/raplaclient.jar HTTP/1.1" 200 0
"HEAD /webclient/javax.inject.jar HTTP/1.1" 200 0
"HEAD /webclient/iText-4.2.0-com.itextpdf.jar HTTP/1.1" 200 0
"HEAD /webclient/super-csv-2.0.1.jar HTTP/1.1" 200 0
"GET /rapla/raplaclient.xconf HTTP/1.1" 200 646
```
* Client side
```
sun.misc.Launcher not found. Running jdk9 or higher? Using unsecure BootClassLoader
Codebase matches codebase manifest attribute, and application is signed. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
Starting application [org.rapla.client.MainWebstart] ...
WARN init: Starting rapla with login screen.
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer createRaplaLogger
INFOS: Logging via java.util.logging API. java.lang.ClassNotFoundException: org.slf4j.Logger
juin 15, 2020 3:21:23 PM org.rapla.framework.internal.RaplaLocaleImpl <init>
INFOS: Configured Locale= fr_BE
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer initialize
INFOS: Config=http:/xxxx.yyyy.zzzz:8051/rapla/raplaclient.xconf
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer initialize
INFOS: Rapla.Version=1.8.6
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer initialize
INFOS: Rapla.Build=2017-02-10 15:25
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer initialize
INFOS: Timezone Europe/Brussels
juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer initialize
INFOS: Java.Version=11.0.7
juin 15, 2020 3:21:23 PM org.rapla.client.internal.RaplaClientServiceImpl init
INFOS: Starting gui 
juin 15, 2020 3:21:23 PM org.rapla.facade.internal.FacadeImpl getOperator
INFOS: Using rapladatasource remotestore
ERROR init: Couldn't start Rapla: org.rapla.facade.internal.FacadeImpl could not be initialized due to null
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:835)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.client.internal.RaplaClientServiceImpl.getFacade(RaplaClientServiceImpl.java:345)
                         org.rapla.client.internal.RaplaClientServiceImpl.start(RaplaClientServiceImpl.java:354)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:101)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:75)
                         org.rapla.client.MainWebstart.main(MainWebstart.java:26)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                         java.base/java.lang.reflect.Method.invoke(Method.java:566)
                         java.desktop/net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
                         java.desktop/net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
 caused by null  null
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                         java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:827)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.client.internal.RaplaClientServiceImpl.getFacade(RaplaClientServiceImpl.java:345)
                         org.rapla.client.internal.RaplaClientServiceImpl.start(RaplaClientServiceImpl.java:354)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:101)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:75)
                         org.rapla.client.MainWebstart.main(MainWebstart.java:26)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                         java.base/java.lang.reflect.Method.invoke(Method.java:566)
                         java.desktop/net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
                         java.desktop/net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
 caused by javax/jws/WebService  javax/jws/WebService
                         org.rapla.framework.internal.ContainerImpl.findDependantConstructor(ContainerImpl.java:716)
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:747)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:119)
                         org.rapla.facade.internal.FacadeImpl.getOperator(FacadeImpl.java:148)
                         org.rapla.facade.internal.FacadeImpl.<init>(FacadeImpl.java:138)
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                         java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:827)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.client.internal.RaplaClientServiceImpl.getFacade(RaplaClientServiceImpl.java:345)
                         org.rapla.client.internal.RaplaClientServiceImpl.start(RaplaClientServiceImpl.java:354)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:101)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:75)
                         org.rapla.client.MainWebstart.main(MainWebstart.java:26)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                         java.base/java.lang.reflect.Method.invoke(Method.java:566)
                         java.desktop/net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
                         java.desktop/net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
 caused by javax.jws.WebService  javax.jws.WebService
                         java.desktop/net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1640)
                         org.rapla.framework.internal.ContainerImpl.findDependantConstructor(ContainerImpl.java:716)
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:747)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:119)
                         org.rapla.facade.internal.FacadeImpl.getOperator(FacadeImpl.java:148)
                         org.rapla.facade.internal.FacadeImpl.<init>(FacadeImpl.java:138)
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                         java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                         org.rapla.framework.internal.ContainerImpl.instanciate(ContainerImpl.java:827)
                         org.rapla.framework.internal.ContainerImpl$ComponentHandler.get(ContainerImpl.java:883)
                         org.rapla.framework.internal.ContainerImpl.lookup(ContainerImpl.java:115)
                         org.rapla.client.internal.RaplaClientServiceImpl.getFacade(RaplaClientServiceImpl.java:345)
                         org.rapla.client.internal.RaplaClientServiceImpl.start(RaplaClientServiceImpl.java:354)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:101)
                         org.rapla.client.MainWebclient.startRapla(MainWebclient.java:75)
                         org.rapla.client.MainWebstart.main(MainWebstart.java:26)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                         java.base/java.lang.reflect.Method.invoke(Method.java:566)
                         java.desktop/net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
                         java.desktop/net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)

juin 15, 2020 3:21:23 PM org.rapla.RaplaMainContainer dispose
INFOS: Shutting down rapla-container
juin 15, 2020 3:21:23 PM org.rapla.framework.internal.ContainerImpl$DefaultScheduler cancel
INFOS: Stopping scheduler thread.
juin 15, 2020 3:21:23 PM org.rapla.framework.internal.ContainerImpl$DefaultScheduler cancel
INFOS: Stopped scheduler thread.
```

I'm unfortunately at a loss with java debugging.
Any idea what's the matter?

Thanks.

**Comment by kohlhaas** [comment]
It seems webstart has a Problem loading. Which java version are you using?

**Comment by quenenni** [comment]
On my debian Buster, i'm using:
icedtea-netx        1.7.2-2           all          Implementation of the Java Network Launching Protocol (JNLP)

And my colleguea has icedtea-netx v1.8.4-1  (Debian testing)

**Comment by quenenni** [comment]
I noticed errors in the rapla log file sometimes when a client try to start the app not always (so not sure if it's related):
```
...
15/juin/2020:16:49:54 +0200 "GET /rapla/raplaclient.xconf HTTP/1.1" 200 646

==> /var/www/rapla/logs/rapla.log <==
16:49:59.672 3584194 [qtp1449263511-89] WARN  o.e.jetty.servlet.ServletHandler - Error for /rapla/json/org.rapla.storage.dbrm.RemoteServer
java.lang.NoClassDefFoundError: javax/jws/WebService
        at org.rapla.rest.gwtjsonrpc.server.JsonServlet.findInterface(JsonServlet.java:656) ~[rapla-1.8.6.jar:na]
        at org.rapla.rest.gwtjsonrpc.server.JsonServlet.methods(JsonServlet.java:637) ~[rapla-1.8.6.jar:na]
        at org.rapla.rest.gwtjsonrpc.server.JsonServlet.<init>(JsonServlet.java:91) ~[rapla-1.8.6.jar:na]
        at org.rapla.rest.server.RaplaAPIPage.getJsonServlet(RaplaAPIPage.java:69) ~[rapla-1.8.6.jar:na]
        at org.rapla.rest.server.RaplaAPIPage.generatePage(RaplaAPIPage.java:89) ~[rapla-1.8.6.jar:na]
        at org.rapla.server.MainServlet.service(MainServlet.java:762) ~[rapla-1.8.6.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[servlet-api-3.0.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.rapla.server.HTTPMethodOverrideFilter.doFilter(HTTPMethodOverrideFilter.java:32) ~[rapla-1.8.6.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) ~[jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) ~[jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) ~[jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) ~[jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) ~[jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) ~[jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) ~[jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Maybe that will give you a hint.

**Comment by quenenni** [comment]
We finally found a way to make it work again.
We had to downgrade java version to openjdk 8 on clients and now it's working again.

List of packages installed on debian:
- openjdk-8-jre-headless amd64 8u232-b09-1~deb9u1
- openjdk-8-jre amd64 8u232-b09-1~deb9u1
- icedtea-netx amd64 1.6.2-3.1+deb9u1
- icedtea-netx-common all 1.6.2-3.1+deb9u1

**Comment by kohlhaas** [comment]
Glad to hear that you could fix it. Was trying to reproduce. Which java version did the clients use that didnt work? Did you have to change versions on the server too?

**Comment by quenenni** [comment]
* Server side:

We updated to openjdk v11.0.7 end of april and the app was still working.
When we heard about that problem, we did a quick test with Rapla v1.8.7 but had the same  problems and went back to 1.8.6 (the active version at the moment).

So nothing obvious on server side.

* Client side

Initially, I had openjdk-11-jre v11.0.7 installed.
I installed first icedtea-netx v1.7.2-2 from Debian Buster.
Then I tried v1.8.4-1 from Debian Sid.
Both these versions of IcedTea used openjdk11 and the app wasn't working.

I finally installed v1.6.2-3.1 from Debian Stretch and it worked.
But it also installed openjdk-8-jre v8u232-b09-1.
