### ISSUE TITLE
Packaging failure, failed tests

### ISSUE THREAD

**Issue by johndoe31415** [rapla/rapla#586]
I'm trying to build Rapla 86e97de29345c8cd3976e5832da4472c224bde22 on Linux x86_64 using OpenJDK 11. My local system timezone is configured to Europe/Berlin per `/etc/timezone`. I cannot package Rapla because the mandatory tests fail:

```
	at org.rapla.storage.impl.AbstractCachableOperator.checkConnected(AbstractCachableOperator.java:556)
	at org.rapla.storage.impl.server.LocalAbstractCachableOperator.getUpdateResult(LocalAbstractCachableOperator.java:3789)
	at org.rapla.storage.impl.server.LocalAbstractCachableOperator.getUpdateResult(LocalAbstractCachableOperator.java:3882)
	at org.rapla.plugin.notification.server.NotificationService.lambda$start$0(NotificationService.java:109)
	at org.rapla.scheduler.CommandScheduler.lambda$schedule$1(CommandScheduler.java:37)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
	at io.reactivex.rxjava3.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDelay$DelaySubscriber.request(FlowableDelay.java:96)
	at io.reactivex.rxjava3.subscribers.SerializedSubscriber.request(SerializedSubscriber.java:195)
	at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:87)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRepeat$RepeatSubscriber.onSubscribe(FlowableRepeat.java:59)
	at io.reactivex.rxjava3.subscribers.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:73)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDelay$DelaySubscriber.onSubscribe(FlowableDelay.java:75)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at org.rapla.scheduler.sync.JavaObservable.subscribe(JavaObservable.java:163)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableScalarXMap$ScalarXMapFlowable.subscribeActual(FlowableScalarXMap.java:160)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDelay.subscribeActual(FlowableDelay.java:50)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRepeat$RepeatSubscriber.subscribeNext(FlowableRepeat.java:101)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRepeat$RepeatSubscriber.onComplete(FlowableRepeat.java:80)
	at io.reactivex.rxjava3.subscribers.SerializedSubscriber.onComplete(SerializedSubscriber.java:171)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDelay$DelaySubscriber$OnComplete.run(FlowableDelay.java:139)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.61 s - in org.rapla.plugin.tests.ICalImportTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ServerTest.testCalendarStore:551 expected:<Thu Sep 12 02:00:00 CEST 2024> but was:<Wed Sep 11 02:00:00 CEST 2024>
[ERROR]   SQLOperatorRemoteTest>ServerTest.testCalendarStore:551 expected:<Thu Sep 12 02:00:00 CEST 2024> but was:<Wed Sep 11 02:00:00 CEST 2024>
[ERROR] Errors: 
[ERROR]   TestUpdateDataManager.testInsertChangeAndDelete:90->testInsertChangeAndDelete:193 » NoSuchElement No attribute found for key name
[INFO] 
[ERROR] Tests run: 187, Failures: 2, Errors: 1, Skipped: 22
```

I.e., some test expects 2024-09-12 to be a Thursday (it is), but the ICAL importer believes it to be a Wednesday (it is not).

I'm skipping tests for now using `mvn package -Dmaven.test.skip`

Thanks,
Johannes

**Comment by kohlhaas** [comment]
Hello Johannes, will look into the test issues. ty

**Comment by johndoe31415** [comment]
Hi Christopher, thanks for the response! If there is anything I can do to support debugging, let me know, I'd be happy to support. Cheers, Johannes

**Comment by kohlhaas** [comment]
Hi Johannes, the Tests are fixed in master now
